function s:setVariable()
    set number
	set relativenumber
	set showmode
	set encoding=utf-8
	set t_Co=256
	set autoindent  "按下回车键 自动和上一行对齐
	set tabstop=4   "tab键的大小
	set laststatus=2
	set statusline=
	set hlsearch
	set mouse=a
	set showtabline=2 "总是显示标签栏
	colorscheme desert

	filetype on "开启文件类型检测
	filetype plugin on  "加载某种类型文件的插件
	filetype indent on  "设置某种类型语言的tab键大小
    syntax on
	execute "normal \<C-w>r"
	"autocmd vimenter * NERDTree
	"execute "NERDTree" "不能执行不知道为什么
	""let &runtimepath = "/data/data/com.termux/home/.vim/plugind"
    call plug#begin("~/.vim/plugind")
		Plug 'itchyny/lightline.vim'
		Plug 'preservim/nerdtree'
	call plug#end()

endfunction


function s:map()
		"map 在normal和visual模式中生效
		"nmap 在normal模式中生效
		"imap 在insert模式中生效
		"vmap 在visual模式中生效
		nnoremap  <Space>h <C-w>h
		nnoremap  <Space>j <C-w>j
		nnoremap  <Space>k <C-w>k
		nnoremap  <Space>l <C-w>l
		nnoremap  tt		  :NERDTree<CR>
		nnoremap  tc 	  	  :NERDTreeClose<CR>
		nnoremap  ss		  :terminal bash<CR><C-w>r<C-w>k:resize +10<CR>
		nnoremap  sc       	  :bwipe! !bash<CR>
		nnoremap  <F9> 	  	  :tabnew<CR>
		nnoremap  <C-h>       :tabp<CR>
		nnoremap  <C-l>       :tabn<CR>

		nnoremap  <C-s>       :w<CR>
		nnoremap  <left>	  <nop>
		nnoremap  <right>	  <nop>
		nnoremap  <up>	      <nop>
		nnoremap  <down>	  <nop>
		
		
		inoremap  ,,		  <ESC>
		inoremap  <ESC>		  <nop>
		inoremap  <up>	      <nop>
		inoremap  <down>	  <nop>
		inoremap  <left>	  <nop>
		inoremap  <right>	  <nop>
		"inoremap  <Tab><Tab>      <C-n>
		"inoremap  <S-n>      <C-n>
		"inoremap  <S-p> 	 <C-p>
		
endfunction

function s:test()
		command Del echo "hello"
endfunction



function s:main()
	call s:setVariable()
	call s:test()
	call s:map()
endfunction


call s:main()
